version: '3'
name: group_8_capstone
services:

  server:
    container_name: "group_8_avs_api"
    image: "ghcr.io/rohitgibson/capstone_group_8:main"
    build: 
      context: .
    ports:
      - 80:80
    networks:
      - avs_internal
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    expose:
      - 6379:6379
      - 8001:8001
    volumes:
      - "./local-data/:/data"
    environment:
      - "REDIS_ARGS=--enable-debug-command yes --enable-module-command yes"
    networks:
      - avs_internal
    restart: on-failure

  nginx:
    image: "nginx"
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - server
    restart: on-failure

    
  
networks:
  avs_internal:
    driver: bridge
    name: avs_internal
    driver_opts:
      gateway: 172.17.0.1

