version: '3'
name: group_8_capstone
services:
  server:
    container_name: "group_8_avs_api"
    image: ghcr.io/rohitgibson/capstone_group_8:main
    build: 
      context: .
    depends_on:
      - redis
    ports:
      - 8000:8000
    networks:
      - avs_network

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    expose:
      - 6379:6379
      - 8001:8001
    volumes:
      - "./local-data/:/data"
    environment:
      - "REDIS_ARGS=--enable-debug-command yes --enable-module-command yes"
    networks:
      - avs_network

  grafana:
    container_name: grafana-dashboards
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    networks:
      - grafana_network

  loki:
    image: grafana/loki:2.9.2
    expose:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana_network

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana_network

networks:
  avs_network:
    driver: bridge
    name: avs_network
  grafana_network:
    driver: bridge
    name: grafana_network
