version: '3'
name: group_8_capstone
services:
  server:
    container_name: "group_8_avs_api"
    image: "ghcr.io/rohitgibson/capstone_group_8:main"
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - avs_internal
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    expose:
      - "6379"
      - "8001"
    volumes:
      - "./local-data/:/data"
    environment:
      - "REDIS_ARGS=--enable-debug-command yes --enable-module-command yes"
    networks:
      - avs_internal
    restart: on-failure
  
networks:
  avs_internal:
    driver: host
    name: avs_internal

